# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Vd8bX6BhfmezyXF5MEndvZvz-ll1cA3
"""

import time
from datetime import datetime, timedelta

i = 1
print('Começou')
while i == 1:  
  time.sleep(5)
  print('10 segundos')

  current_time = datetime.now()    
  f_data = current_time.strftime("%Y-%m-%d T%H:%M:%S.%fZ")
  print("formated date: "+str(f_data))
  print('-----------')
